#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evolution_gym.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="idmanzali")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFilial(Filial instance);
    partial void UpdateFilial(Filial instance);
    partial void DeleteFilial(Filial instance);
    partial void InsertVezife(Vezife instance);
    partial void UpdateVezife(Vezife instance);
    partial void DeleteVezife(Vezife instance);
    partial void InsertIsci(Isci instance);
    partial void UpdateIsci(Isci instance);
    partial void DeleteIsci(Isci instance);
    partial void InsertTelebe(Telebe instance);
    partial void UpdateTelebe(Telebe instance);
    partial void DeleteTelebe(Telebe instance);
    partial void InsertTrainer(Trainer instance);
    partial void UpdateTrainer(Trainer instance);
    partial void DeleteTrainer(Trainer instance);
    partial void InsertComunal(Comunal instance);
    partial void UpdateComunal(Comunal instance);
    partial void DeleteComunal(Comunal instance);
    partial void InsertArenda(Arenda instance);
    partial void UpdateArenda(Arenda instance);
    partial void DeleteArenda(Arenda instance);
    #endregion
		
		public DataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["idmanzaliConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Filial> Filials
		{
			get
			{
				return this.GetTable<Filial>();
			}
		}
		
		public System.Data.Linq.Table<Vezife> Vezifes
		{
			get
			{
				return this.GetTable<Vezife>();
			}
		}
		
		public System.Data.Linq.Table<Isci> Iscis
		{
			get
			{
				return this.GetTable<Isci>();
			}
		}
		
		public System.Data.Linq.Table<IsciMain> IsciMains
		{
			get
			{
				return this.GetTable<IsciMain>();
			}
		}
		
		public System.Data.Linq.Table<TelebeMain> TelebeMains
		{
			get
			{
				return this.GetTable<TelebeMain>();
			}
		}
		
		public System.Data.Linq.Table<Telebe> Telebes
		{
			get
			{
				return this.GetTable<Telebe>();
			}
		}
		
		public System.Data.Linq.Table<Trainer> Trainers
		{
			get
			{
				return this.GetTable<Trainer>();
			}
		}
		
		public System.Data.Linq.Table<Comunal> Comunals
		{
			get
			{
				return this.GetTable<Comunal>();
			}
		}
		
		public System.Data.Linq.Table<ComunalMain> ComunalMains
		{
			get
			{
				return this.GetTable<ComunalMain>();
			}
		}
		
		public System.Data.Linq.Table<Arenda> Arendas
		{
			get
			{
				return this.GetTable<Arenda>();
			}
		}
		
		public System.Data.Linq.Table<ArendaMain> ArendaMains
		{
			get
			{
				return this.GetTable<ArendaMain>();
			}
		}
		
		public System.Data.Linq.Table<Bildiri> Bildiris
		{
			get
			{
				return this.GetTable<Bildiri>();
			}
		}
		
		public System.Data.Linq.Table<IsciBildiri> IsciBildiris
		{
			get
			{
				return this.GetTable<IsciBildiri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Filial")]
	public partial class Filial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FilialId;
		
		private string _FilialAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFilialIdChanging(int value);
    partial void OnFilialIdChanged();
    partial void OnFilialAdChanging(string value);
    partial void OnFilialAdChanged();
    #endregion
		
		public Filial()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FilialId
		{
			get
			{
				return this._FilialId;
			}
			set
			{
				if ((this._FilialId != value))
				{
					this.OnFilialIdChanging(value);
					this.SendPropertyChanging();
					this._FilialId = value;
					this.SendPropertyChanged("FilialId");
					this.OnFilialIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialAd", DbType="NVarChar(30)")]
		public string FilialAd
		{
			get
			{
				return this._FilialAd;
			}
			set
			{
				if ((this._FilialAd != value))
				{
					this.OnFilialAdChanging(value);
					this.SendPropertyChanging();
					this._FilialAd = value;
					this.SendPropertyChanged("FilialAd");
					this.OnFilialAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vezife")]
	public partial class Vezife : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VezifeId;
		
		private string _VezifeAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVezifeIdChanging(int value);
    partial void OnVezifeIdChanged();
    partial void OnVezifeAdChanging(string value);
    partial void OnVezifeAdChanged();
    #endregion
		
		public Vezife()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VezifeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VezifeId
		{
			get
			{
				return this._VezifeId;
			}
			set
			{
				if ((this._VezifeId != value))
				{
					this.OnVezifeIdChanging(value);
					this.SendPropertyChanging();
					this._VezifeId = value;
					this.SendPropertyChanged("VezifeId");
					this.OnVezifeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VezifeAd", DbType="NVarChar(30)")]
		public string VezifeAd
		{
			get
			{
				return this._VezifeAd;
			}
			set
			{
				if ((this._VezifeAd != value))
				{
					this.OnVezifeAdChanging(value);
					this.SendPropertyChanging();
					this._VezifeAd = value;
					this.SendPropertyChanged("VezifeAd");
					this.OnVezifeAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Isci")]
	public partial class Isci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IsciId;
		
		private string _IsciAd;
		
		private string _IsciSoyad;
		
		private System.Nullable<System.DateTime> _IsciIseBaslamaTarixi;
		
		private System.Nullable<double> _IsciResmiMaas;
		
		private System.Nullable<double> _IsciMotivasiyaMaas;
		
		private System.Nullable<int> _IsciVezifeId;
		
		private System.Nullable<int> _IsciFilialId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIsciIdChanging(int value);
    partial void OnIsciIdChanged();
    partial void OnIsciAdChanging(string value);
    partial void OnIsciAdChanged();
    partial void OnIsciSoyadChanging(string value);
    partial void OnIsciSoyadChanged();
    partial void OnIsciIseBaslamaTarixiChanging(System.Nullable<System.DateTime> value);
    partial void OnIsciIseBaslamaTarixiChanged();
    partial void OnIsciResmiMaasChanging(System.Nullable<double> value);
    partial void OnIsciResmiMaasChanged();
    partial void OnIsciMotivasiyaMaasChanging(System.Nullable<double> value);
    partial void OnIsciMotivasiyaMaasChanged();
    partial void OnIsciVezifeIdChanging(System.Nullable<int> value);
    partial void OnIsciVezifeIdChanged();
    partial void OnIsciFilialIdChanging(System.Nullable<int> value);
    partial void OnIsciFilialIdChanged();
    #endregion
		
		public Isci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IsciId
		{
			get
			{
				return this._IsciId;
			}
			set
			{
				if ((this._IsciId != value))
				{
					this.OnIsciIdChanging(value);
					this.SendPropertyChanging();
					this._IsciId = value;
					this.SendPropertyChanged("IsciId");
					this.OnIsciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciAd", DbType="NVarChar(20)")]
		public string IsciAd
		{
			get
			{
				return this._IsciAd;
			}
			set
			{
				if ((this._IsciAd != value))
				{
					this.OnIsciAdChanging(value);
					this.SendPropertyChanging();
					this._IsciAd = value;
					this.SendPropertyChanged("IsciAd");
					this.OnIsciAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciSoyad", DbType="NVarChar(20)")]
		public string IsciSoyad
		{
			get
			{
				return this._IsciSoyad;
			}
			set
			{
				if ((this._IsciSoyad != value))
				{
					this.OnIsciSoyadChanging(value);
					this.SendPropertyChanging();
					this._IsciSoyad = value;
					this.SendPropertyChanged("IsciSoyad");
					this.OnIsciSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciIseBaslamaTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IsciIseBaslamaTarixi
		{
			get
			{
				return this._IsciIseBaslamaTarixi;
			}
			set
			{
				if ((this._IsciIseBaslamaTarixi != value))
				{
					this.OnIsciIseBaslamaTarixiChanging(value);
					this.SendPropertyChanging();
					this._IsciIseBaslamaTarixi = value;
					this.SendPropertyChanged("IsciIseBaslamaTarixi");
					this.OnIsciIseBaslamaTarixiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciResmiMaas", DbType="Float")]
		public System.Nullable<double> IsciResmiMaas
		{
			get
			{
				return this._IsciResmiMaas;
			}
			set
			{
				if ((this._IsciResmiMaas != value))
				{
					this.OnIsciResmiMaasChanging(value);
					this.SendPropertyChanging();
					this._IsciResmiMaas = value;
					this.SendPropertyChanged("IsciResmiMaas");
					this.OnIsciResmiMaasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciMotivasiyaMaas", DbType="Float")]
		public System.Nullable<double> IsciMotivasiyaMaas
		{
			get
			{
				return this._IsciMotivasiyaMaas;
			}
			set
			{
				if ((this._IsciMotivasiyaMaas != value))
				{
					this.OnIsciMotivasiyaMaasChanging(value);
					this.SendPropertyChanging();
					this._IsciMotivasiyaMaas = value;
					this.SendPropertyChanged("IsciMotivasiyaMaas");
					this.OnIsciMotivasiyaMaasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciVezifeId", DbType="Int")]
		public System.Nullable<int> IsciVezifeId
		{
			get
			{
				return this._IsciVezifeId;
			}
			set
			{
				if ((this._IsciVezifeId != value))
				{
					this.OnIsciVezifeIdChanging(value);
					this.SendPropertyChanging();
					this._IsciVezifeId = value;
					this.SendPropertyChanged("IsciVezifeId");
					this.OnIsciVezifeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciFilialId", DbType="Int")]
		public System.Nullable<int> IsciFilialId
		{
			get
			{
				return this._IsciFilialId;
			}
			set
			{
				if ((this._IsciFilialId != value))
				{
					this.OnIsciFilialIdChanging(value);
					this.SendPropertyChanging();
					this._IsciFilialId = value;
					this.SendPropertyChanged("IsciFilialId");
					this.OnIsciFilialIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IsciMain")]
	public partial class IsciMain
	{
		
		private int _IsciId;
		
		private string _IsciAd;
		
		private string _IsciSoyad;
		
		private System.Nullable<System.DateTime> _IsciIseBaslamaTarixi;
		
		private System.Nullable<double> _IsciResmiMaas;
		
		private System.Nullable<double> _IsciMotivasiyaMaas;
		
		private System.Nullable<int> _IsciVezifeId;
		
		private System.Nullable<int> _IsciFilialId;
		
		private System.Nullable<int> _VezifeId;
		
		private string _VezifeAd;
		
		private System.Nullable<int> _FilialId;
		
		private string _FilialAd;
		
		public IsciMain()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciId", DbType="Int NOT NULL")]
		public int IsciId
		{
			get
			{
				return this._IsciId;
			}
			set
			{
				if ((this._IsciId != value))
				{
					this._IsciId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciAd", DbType="NVarChar(20)")]
		public string IsciAd
		{
			get
			{
				return this._IsciAd;
			}
			set
			{
				if ((this._IsciAd != value))
				{
					this._IsciAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciSoyad", DbType="NVarChar(20)")]
		public string IsciSoyad
		{
			get
			{
				return this._IsciSoyad;
			}
			set
			{
				if ((this._IsciSoyad != value))
				{
					this._IsciSoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciIseBaslamaTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IsciIseBaslamaTarixi
		{
			get
			{
				return this._IsciIseBaslamaTarixi;
			}
			set
			{
				if ((this._IsciIseBaslamaTarixi != value))
				{
					this._IsciIseBaslamaTarixi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciResmiMaas", DbType="Float")]
		public System.Nullable<double> IsciResmiMaas
		{
			get
			{
				return this._IsciResmiMaas;
			}
			set
			{
				if ((this._IsciResmiMaas != value))
				{
					this._IsciResmiMaas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciMotivasiyaMaas", DbType="Float")]
		public System.Nullable<double> IsciMotivasiyaMaas
		{
			get
			{
				return this._IsciMotivasiyaMaas;
			}
			set
			{
				if ((this._IsciMotivasiyaMaas != value))
				{
					this._IsciMotivasiyaMaas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciVezifeId", DbType="Int")]
		public System.Nullable<int> IsciVezifeId
		{
			get
			{
				return this._IsciVezifeId;
			}
			set
			{
				if ((this._IsciVezifeId != value))
				{
					this._IsciVezifeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciFilialId", DbType="Int")]
		public System.Nullable<int> IsciFilialId
		{
			get
			{
				return this._IsciFilialId;
			}
			set
			{
				if ((this._IsciFilialId != value))
				{
					this._IsciFilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VezifeId", DbType="Int")]
		public System.Nullable<int> VezifeId
		{
			get
			{
				return this._VezifeId;
			}
			set
			{
				if ((this._VezifeId != value))
				{
					this._VezifeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VezifeAd", DbType="NVarChar(30)")]
		public string VezifeAd
		{
			get
			{
				return this._VezifeAd;
			}
			set
			{
				if ((this._VezifeAd != value))
				{
					this._VezifeAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialId", DbType="Int")]
		public System.Nullable<int> FilialId
		{
			get
			{
				return this._FilialId;
			}
			set
			{
				if ((this._FilialId != value))
				{
					this._FilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialAd", DbType="NVarChar(30)")]
		public string FilialAd
		{
			get
			{
				return this._FilialAd;
			}
			set
			{
				if ((this._FilialAd != value))
				{
					this._FilialAd = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TelebeMain")]
	public partial class TelebeMain
	{
		
		private int _Telebeİd;
		
		private string _TelebeAd;
		
		private string _TelebeSoyad;
		
		private System.Nullable<System.DateTime> _TelebeMesqeBaslamaTarixi;
		
		private System.Nullable<double> _TelebeAyliqOdenis;
		
		private System.Nullable<int> _TelebeFilialId;
		
		private System.Nullable<int> _TelebeTrainerId;
		
		private System.Nullable<int> _FilialId;
		
		private string _FilialAd;
		
		private System.Nullable<int> _TrainerId;
		
		private string _TrainerAd;
		
		private string _TrainerSoyad;
		
		public TelebeMain()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telebeİd", DbType="Int NOT NULL")]
		public int Telebeİd
		{
			get
			{
				return this._Telebeİd;
			}
			set
			{
				if ((this._Telebeİd != value))
				{
					this._Telebeİd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeAd", DbType="NVarChar(20)")]
		public string TelebeAd
		{
			get
			{
				return this._TelebeAd;
			}
			set
			{
				if ((this._TelebeAd != value))
				{
					this._TelebeAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeSoyad", DbType="NVarChar(20)")]
		public string TelebeSoyad
		{
			get
			{
				return this._TelebeSoyad;
			}
			set
			{
				if ((this._TelebeSoyad != value))
				{
					this._TelebeSoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeMesqeBaslamaTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TelebeMesqeBaslamaTarixi
		{
			get
			{
				return this._TelebeMesqeBaslamaTarixi;
			}
			set
			{
				if ((this._TelebeMesqeBaslamaTarixi != value))
				{
					this._TelebeMesqeBaslamaTarixi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeAyliqOdenis", DbType="Float")]
		public System.Nullable<double> TelebeAyliqOdenis
		{
			get
			{
				return this._TelebeAyliqOdenis;
			}
			set
			{
				if ((this._TelebeAyliqOdenis != value))
				{
					this._TelebeAyliqOdenis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeFilialId", DbType="Int")]
		public System.Nullable<int> TelebeFilialId
		{
			get
			{
				return this._TelebeFilialId;
			}
			set
			{
				if ((this._TelebeFilialId != value))
				{
					this._TelebeFilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeTrainerId", DbType="Int")]
		public System.Nullable<int> TelebeTrainerId
		{
			get
			{
				return this._TelebeTrainerId;
			}
			set
			{
				if ((this._TelebeTrainerId != value))
				{
					this._TelebeTrainerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialId", DbType="Int")]
		public System.Nullable<int> FilialId
		{
			get
			{
				return this._FilialId;
			}
			set
			{
				if ((this._FilialId != value))
				{
					this._FilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialAd", DbType="NVarChar(30)")]
		public string FilialAd
		{
			get
			{
				return this._FilialAd;
			}
			set
			{
				if ((this._FilialAd != value))
				{
					this._FilialAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainerId", DbType="Int")]
		public System.Nullable<int> TrainerId
		{
			get
			{
				return this._TrainerId;
			}
			set
			{
				if ((this._TrainerId != value))
				{
					this._TrainerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainerAd", DbType="NVarChar(20)")]
		public string TrainerAd
		{
			get
			{
				return this._TrainerAd;
			}
			set
			{
				if ((this._TrainerAd != value))
				{
					this._TrainerAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainerSoyad", DbType="NVarChar(20)")]
		public string TrainerSoyad
		{
			get
			{
				return this._TrainerSoyad;
			}
			set
			{
				if ((this._TrainerSoyad != value))
				{
					this._TrainerSoyad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Telebe")]
	public partial class Telebe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Telebeİd;
		
		private string _TelebeAd;
		
		private string _TelebeSoyad;
		
		private System.Nullable<System.DateTime> _TelebeMesqeBaslamaTarixi;
		
		private System.Nullable<double> _TelebeAyliqOdenis;
		
		private System.Nullable<int> _TelebeFilialId;
		
		private System.Nullable<int> _TelebeTrainerId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTelebeİdChanging(int value);
    partial void OnTelebeİdChanged();
    partial void OnTelebeAdChanging(string value);
    partial void OnTelebeAdChanged();
    partial void OnTelebeSoyadChanging(string value);
    partial void OnTelebeSoyadChanged();
    partial void OnTelebeMesqeBaslamaTarixiChanging(System.Nullable<System.DateTime> value);
    partial void OnTelebeMesqeBaslamaTarixiChanged();
    partial void OnTelebeAyliqOdenisChanging(System.Nullable<double> value);
    partial void OnTelebeAyliqOdenisChanged();
    partial void OnTelebeFilialIdChanging(System.Nullable<int> value);
    partial void OnTelebeFilialIdChanged();
    partial void OnTelebeTrainerIdChanging(System.Nullable<int> value);
    partial void OnTelebeTrainerIdChanged();
    #endregion
		
		public Telebe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telebeİd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Telebeİd
		{
			get
			{
				return this._Telebeİd;
			}
			set
			{
				if ((this._Telebeİd != value))
				{
					this.OnTelebeİdChanging(value);
					this.SendPropertyChanging();
					this._Telebeİd = value;
					this.SendPropertyChanged("Telebeİd");
					this.OnTelebeİdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeAd", DbType="NVarChar(20)")]
		public string TelebeAd
		{
			get
			{
				return this._TelebeAd;
			}
			set
			{
				if ((this._TelebeAd != value))
				{
					this.OnTelebeAdChanging(value);
					this.SendPropertyChanging();
					this._TelebeAd = value;
					this.SendPropertyChanged("TelebeAd");
					this.OnTelebeAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeSoyad", DbType="NVarChar(20)")]
		public string TelebeSoyad
		{
			get
			{
				return this._TelebeSoyad;
			}
			set
			{
				if ((this._TelebeSoyad != value))
				{
					this.OnTelebeSoyadChanging(value);
					this.SendPropertyChanging();
					this._TelebeSoyad = value;
					this.SendPropertyChanged("TelebeSoyad");
					this.OnTelebeSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeMesqeBaslamaTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TelebeMesqeBaslamaTarixi
		{
			get
			{
				return this._TelebeMesqeBaslamaTarixi;
			}
			set
			{
				if ((this._TelebeMesqeBaslamaTarixi != value))
				{
					this.OnTelebeMesqeBaslamaTarixiChanging(value);
					this.SendPropertyChanging();
					this._TelebeMesqeBaslamaTarixi = value;
					this.SendPropertyChanged("TelebeMesqeBaslamaTarixi");
					this.OnTelebeMesqeBaslamaTarixiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeAyliqOdenis", DbType="Float")]
		public System.Nullable<double> TelebeAyliqOdenis
		{
			get
			{
				return this._TelebeAyliqOdenis;
			}
			set
			{
				if ((this._TelebeAyliqOdenis != value))
				{
					this.OnTelebeAyliqOdenisChanging(value);
					this.SendPropertyChanging();
					this._TelebeAyliqOdenis = value;
					this.SendPropertyChanged("TelebeAyliqOdenis");
					this.OnTelebeAyliqOdenisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeFilialId", DbType="Int")]
		public System.Nullable<int> TelebeFilialId
		{
			get
			{
				return this._TelebeFilialId;
			}
			set
			{
				if ((this._TelebeFilialId != value))
				{
					this.OnTelebeFilialIdChanging(value);
					this.SendPropertyChanging();
					this._TelebeFilialId = value;
					this.SendPropertyChanged("TelebeFilialId");
					this.OnTelebeFilialIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeTrainerId", DbType="Int")]
		public System.Nullable<int> TelebeTrainerId
		{
			get
			{
				return this._TelebeTrainerId;
			}
			set
			{
				if ((this._TelebeTrainerId != value))
				{
					this.OnTelebeTrainerIdChanging(value);
					this.SendPropertyChanging();
					this._TelebeTrainerId = value;
					this.SendPropertyChanged("TelebeTrainerId");
					this.OnTelebeTrainerIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trainer")]
	public partial class Trainer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TrainerId;
		
		private string _TrainerAd;
		
		private string _TrainerSoyad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrainerIdChanging(int value);
    partial void OnTrainerIdChanged();
    partial void OnTrainerAdChanging(string value);
    partial void OnTrainerAdChanged();
    partial void OnTrainerSoyadChanging(string value);
    partial void OnTrainerSoyadChanged();
    #endregion
		
		public Trainer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TrainerId
		{
			get
			{
				return this._TrainerId;
			}
			set
			{
				if ((this._TrainerId != value))
				{
					this.OnTrainerIdChanging(value);
					this.SendPropertyChanging();
					this._TrainerId = value;
					this.SendPropertyChanged("TrainerId");
					this.OnTrainerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainerAd", DbType="NVarChar(20)")]
		public string TrainerAd
		{
			get
			{
				return this._TrainerAd;
			}
			set
			{
				if ((this._TrainerAd != value))
				{
					this.OnTrainerAdChanging(value);
					this.SendPropertyChanging();
					this._TrainerAd = value;
					this.SendPropertyChanged("TrainerAd");
					this.OnTrainerAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainerSoyad", DbType="NVarChar(20)")]
		public string TrainerSoyad
		{
			get
			{
				return this._TrainerSoyad;
			}
			set
			{
				if ((this._TrainerSoyad != value))
				{
					this.OnTrainerSoyadChanging(value);
					this.SendPropertyChanging();
					this._TrainerSoyad = value;
					this.SendPropertyChanged("TrainerSoyad");
					this.OnTrainerSoyadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comunal")]
	public partial class Comunal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ComunalId;
		
		private string _ComunalAd;
		
		private System.Nullable<System.DateTime> _ComunalTarix;
		
		private System.Nullable<double> _ComunalMiqdar;
		
		private System.Nullable<int> _ComunalFilialId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComunalIdChanging(int value);
    partial void OnComunalIdChanged();
    partial void OnComunalAdChanging(string value);
    partial void OnComunalAdChanged();
    partial void OnComunalTarixChanging(System.Nullable<System.DateTime> value);
    partial void OnComunalTarixChanged();
    partial void OnComunalMiqdarChanging(System.Nullable<double> value);
    partial void OnComunalMiqdarChanged();
    partial void OnComunalFilialIdChanging(System.Nullable<int> value);
    partial void OnComunalFilialIdChanged();
    #endregion
		
		public Comunal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ComunalId
		{
			get
			{
				return this._ComunalId;
			}
			set
			{
				if ((this._ComunalId != value))
				{
					this.OnComunalIdChanging(value);
					this.SendPropertyChanging();
					this._ComunalId = value;
					this.SendPropertyChanged("ComunalId");
					this.OnComunalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalAd", DbType="NVarChar(50)")]
		public string ComunalAd
		{
			get
			{
				return this._ComunalAd;
			}
			set
			{
				if ((this._ComunalAd != value))
				{
					this.OnComunalAdChanging(value);
					this.SendPropertyChanging();
					this._ComunalAd = value;
					this.SendPropertyChanged("ComunalAd");
					this.OnComunalAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalTarix", DbType="DateTime")]
		public System.Nullable<System.DateTime> ComunalTarix
		{
			get
			{
				return this._ComunalTarix;
			}
			set
			{
				if ((this._ComunalTarix != value))
				{
					this.OnComunalTarixChanging(value);
					this.SendPropertyChanging();
					this._ComunalTarix = value;
					this.SendPropertyChanged("ComunalTarix");
					this.OnComunalTarixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalMiqdar", DbType="Float")]
		public System.Nullable<double> ComunalMiqdar
		{
			get
			{
				return this._ComunalMiqdar;
			}
			set
			{
				if ((this._ComunalMiqdar != value))
				{
					this.OnComunalMiqdarChanging(value);
					this.SendPropertyChanging();
					this._ComunalMiqdar = value;
					this.SendPropertyChanged("ComunalMiqdar");
					this.OnComunalMiqdarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalFilialId", DbType="Int")]
		public System.Nullable<int> ComunalFilialId
		{
			get
			{
				return this._ComunalFilialId;
			}
			set
			{
				if ((this._ComunalFilialId != value))
				{
					this.OnComunalFilialIdChanging(value);
					this.SendPropertyChanging();
					this._ComunalFilialId = value;
					this.SendPropertyChanged("ComunalFilialId");
					this.OnComunalFilialIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ComunalMain")]
	public partial class ComunalMain
	{
		
		private int _ComunalId;
		
		private string _ComunalAd;
		
		private System.Nullable<System.DateTime> _ComunalTarix;
		
		private System.Nullable<double> _ComunalMiqdar;
		
		private System.Nullable<int> _ComunalFilialId;
		
		private System.Nullable<int> _FilialId;
		
		private string _FilialAd;
		
		public ComunalMain()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalId", DbType="Int NOT NULL")]
		public int ComunalId
		{
			get
			{
				return this._ComunalId;
			}
			set
			{
				if ((this._ComunalId != value))
				{
					this._ComunalId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalAd", DbType="NVarChar(50)")]
		public string ComunalAd
		{
			get
			{
				return this._ComunalAd;
			}
			set
			{
				if ((this._ComunalAd != value))
				{
					this._ComunalAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalTarix", DbType="DateTime")]
		public System.Nullable<System.DateTime> ComunalTarix
		{
			get
			{
				return this._ComunalTarix;
			}
			set
			{
				if ((this._ComunalTarix != value))
				{
					this._ComunalTarix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalMiqdar", DbType="Float")]
		public System.Nullable<double> ComunalMiqdar
		{
			get
			{
				return this._ComunalMiqdar;
			}
			set
			{
				if ((this._ComunalMiqdar != value))
				{
					this._ComunalMiqdar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunalFilialId", DbType="Int")]
		public System.Nullable<int> ComunalFilialId
		{
			get
			{
				return this._ComunalFilialId;
			}
			set
			{
				if ((this._ComunalFilialId != value))
				{
					this._ComunalFilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialId", DbType="Int")]
		public System.Nullable<int> FilialId
		{
			get
			{
				return this._FilialId;
			}
			set
			{
				if ((this._FilialId != value))
				{
					this._FilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialAd", DbType="NVarChar(30)")]
		public string FilialAd
		{
			get
			{
				return this._FilialAd;
			}
			set
			{
				if ((this._FilialAd != value))
				{
					this._FilialAd = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Arenda")]
	public partial class Arenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ArendaId;
		
		private System.Nullable<int> _ArendaFilialId;
		
		private System.Nullable<System.DateTime> _ArendaOdenisTarixi;
		
		private System.Nullable<double> _ArendaAyliqOdenis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnArendaIdChanging(int value);
    partial void OnArendaIdChanged();
    partial void OnArendaFilialIdChanging(System.Nullable<int> value);
    partial void OnArendaFilialIdChanged();
    partial void OnArendaOdenisTarixiChanging(System.Nullable<System.DateTime> value);
    partial void OnArendaOdenisTarixiChanged();
    partial void OnArendaAyliqOdenisChanging(System.Nullable<double> value);
    partial void OnArendaAyliqOdenisChanged();
    #endregion
		
		public Arenda()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ArendaId
		{
			get
			{
				return this._ArendaId;
			}
			set
			{
				if ((this._ArendaId != value))
				{
					this.OnArendaIdChanging(value);
					this.SendPropertyChanging();
					this._ArendaId = value;
					this.SendPropertyChanged("ArendaId");
					this.OnArendaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaFilialId", DbType="Int")]
		public System.Nullable<int> ArendaFilialId
		{
			get
			{
				return this._ArendaFilialId;
			}
			set
			{
				if ((this._ArendaFilialId != value))
				{
					this.OnArendaFilialIdChanging(value);
					this.SendPropertyChanging();
					this._ArendaFilialId = value;
					this.SendPropertyChanged("ArendaFilialId");
					this.OnArendaFilialIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaOdenisTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ArendaOdenisTarixi
		{
			get
			{
				return this._ArendaOdenisTarixi;
			}
			set
			{
				if ((this._ArendaOdenisTarixi != value))
				{
					this.OnArendaOdenisTarixiChanging(value);
					this.SendPropertyChanging();
					this._ArendaOdenisTarixi = value;
					this.SendPropertyChanged("ArendaOdenisTarixi");
					this.OnArendaOdenisTarixiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaAyliqOdenis", DbType="Float")]
		public System.Nullable<double> ArendaAyliqOdenis
		{
			get
			{
				return this._ArendaAyliqOdenis;
			}
			set
			{
				if ((this._ArendaAyliqOdenis != value))
				{
					this.OnArendaAyliqOdenisChanging(value);
					this.SendPropertyChanging();
					this._ArendaAyliqOdenis = value;
					this.SendPropertyChanged("ArendaAyliqOdenis");
					this.OnArendaAyliqOdenisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ArendaMain")]
	public partial class ArendaMain
	{
		
		private int _ArendaId;
		
		private System.Nullable<int> _ArendaFilialId;
		
		private System.Nullable<System.DateTime> _ArendaOdenisTarixi;
		
		private System.Nullable<double> _ArendaAyliqOdenis;
		
		private System.Nullable<int> _FilialId;
		
		private string _FilialAd;
		
		public ArendaMain()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaId", DbType="Int NOT NULL")]
		public int ArendaId
		{
			get
			{
				return this._ArendaId;
			}
			set
			{
				if ((this._ArendaId != value))
				{
					this._ArendaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaFilialId", DbType="Int")]
		public System.Nullable<int> ArendaFilialId
		{
			get
			{
				return this._ArendaFilialId;
			}
			set
			{
				if ((this._ArendaFilialId != value))
				{
					this._ArendaFilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaOdenisTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ArendaOdenisTarixi
		{
			get
			{
				return this._ArendaOdenisTarixi;
			}
			set
			{
				if ((this._ArendaOdenisTarixi != value))
				{
					this._ArendaOdenisTarixi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArendaAyliqOdenis", DbType="Float")]
		public System.Nullable<double> ArendaAyliqOdenis
		{
			get
			{
				return this._ArendaAyliqOdenis;
			}
			set
			{
				if ((this._ArendaAyliqOdenis != value))
				{
					this._ArendaAyliqOdenis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialId", DbType="Int")]
		public System.Nullable<int> FilialId
		{
			get
			{
				return this._FilialId;
			}
			set
			{
				if ((this._FilialId != value))
				{
					this._FilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilialAd", DbType="NVarChar(30)")]
		public string FilialAd
		{
			get
			{
				return this._FilialAd;
			}
			set
			{
				if ((this._FilialAd != value))
				{
					this._FilialAd = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bildiris")]
	public partial class Bildiri
	{
		
		private int _Telebeİd;
		
		private string _TelebeAd;
		
		private string _TelebeSoyad;
		
		private System.Nullable<System.DateTime> _TelebeMesqeBaslamaTarixi;
		
		private System.Nullable<double> _TelebeAyliqOdenis;
		
		private System.Nullable<int> _TelebeFilialId;
		
		private System.Nullable<int> _TelebeTrainerId;
		
		public Bildiri()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telebeİd", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Telebeİd
		{
			get
			{
				return this._Telebeİd;
			}
			set
			{
				if ((this._Telebeİd != value))
				{
					this._Telebeİd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeAd", DbType="NVarChar(20)")]
		public string TelebeAd
		{
			get
			{
				return this._TelebeAd;
			}
			set
			{
				if ((this._TelebeAd != value))
				{
					this._TelebeAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeSoyad", DbType="NVarChar(20)")]
		public string TelebeSoyad
		{
			get
			{
				return this._TelebeSoyad;
			}
			set
			{
				if ((this._TelebeSoyad != value))
				{
					this._TelebeSoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeMesqeBaslamaTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TelebeMesqeBaslamaTarixi
		{
			get
			{
				return this._TelebeMesqeBaslamaTarixi;
			}
			set
			{
				if ((this._TelebeMesqeBaslamaTarixi != value))
				{
					this._TelebeMesqeBaslamaTarixi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeAyliqOdenis", DbType="Float")]
		public System.Nullable<double> TelebeAyliqOdenis
		{
			get
			{
				return this._TelebeAyliqOdenis;
			}
			set
			{
				if ((this._TelebeAyliqOdenis != value))
				{
					this._TelebeAyliqOdenis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeFilialId", DbType="Int")]
		public System.Nullable<int> TelebeFilialId
		{
			get
			{
				return this._TelebeFilialId;
			}
			set
			{
				if ((this._TelebeFilialId != value))
				{
					this._TelebeFilialId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelebeTrainerId", DbType="Int")]
		public System.Nullable<int> TelebeTrainerId
		{
			get
			{
				return this._TelebeTrainerId;
			}
			set
			{
				if ((this._TelebeTrainerId != value))
				{
					this._TelebeTrainerId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IsciBildiris")]
	public partial class IsciBildiri
	{
		
		private int _IsciId;
		
		private string _IsciAd;
		
		private string _IsciSoyad;
		
		private System.Nullable<System.DateTime> _IsciIseBaslamaTarixi;
		
		private System.Nullable<double> _IsciResmiMaas;
		
		private System.Nullable<double> _IsciMotivasiyaMaas;
		
		private System.Nullable<int> _IsciVezifeId;
		
		private System.Nullable<int> _IsciFilialId;
		
		public IsciBildiri()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IsciId
		{
			get
			{
				return this._IsciId;
			}
			set
			{
				if ((this._IsciId != value))
				{
					this._IsciId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciAd", DbType="NVarChar(20)")]
		public string IsciAd
		{
			get
			{
				return this._IsciAd;
			}
			set
			{
				if ((this._IsciAd != value))
				{
					this._IsciAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciSoyad", DbType="NVarChar(20)")]
		public string IsciSoyad
		{
			get
			{
				return this._IsciSoyad;
			}
			set
			{
				if ((this._IsciSoyad != value))
				{
					this._IsciSoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciIseBaslamaTarixi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IsciIseBaslamaTarixi
		{
			get
			{
				return this._IsciIseBaslamaTarixi;
			}
			set
			{
				if ((this._IsciIseBaslamaTarixi != value))
				{
					this._IsciIseBaslamaTarixi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciResmiMaas", DbType="Float")]
		public System.Nullable<double> IsciResmiMaas
		{
			get
			{
				return this._IsciResmiMaas;
			}
			set
			{
				if ((this._IsciResmiMaas != value))
				{
					this._IsciResmiMaas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciMotivasiyaMaas", DbType="Float")]
		public System.Nullable<double> IsciMotivasiyaMaas
		{
			get
			{
				return this._IsciMotivasiyaMaas;
			}
			set
			{
				if ((this._IsciMotivasiyaMaas != value))
				{
					this._IsciMotivasiyaMaas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciVezifeId", DbType="Int")]
		public System.Nullable<int> IsciVezifeId
		{
			get
			{
				return this._IsciVezifeId;
			}
			set
			{
				if ((this._IsciVezifeId != value))
				{
					this._IsciVezifeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsciFilialId", DbType="Int")]
		public System.Nullable<int> IsciFilialId
		{
			get
			{
				return this._IsciFilialId;
			}
			set
			{
				if ((this._IsciFilialId != value))
				{
					this._IsciFilialId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
